### ISSUE TITLE
add research.udp-perf

### ISSUE THREAD

**Issue by sgf** [JohannesDeml/NetworkBenchmarkDotNet#14]
https://github.com/enclave-networks/research.udp-perf

**Comment by JohannesDeml** [comment]
I saw this repo quite some time ago. It uses .NET 5 specific features, that will not be compatible with Unity and it does not have any support for reliable messages, but it might still be interesting to see a comparison. Are you up for the task of implementing it? You can find a guidance for implementing a new library here: https://github.com/JohannesDeml/NetworkBenchmarkDotNet#how-to-add-a-library

**Comment by sgf** [comment]
ok,thank you,if i have time,i will add that code into this library
